app:
  mode: debug 
  BasicAuth: '{"admin":"123456"}'
storybox:
  cms:
    url: http://cms.roobo.net/api/app/copy
    supertoken: b9b065fe0714d483aa4146bb715f9895
  toolkit:
    database:
      name: toolkit 
      type: mysql
      host: mysql.localhost
      port: 3306
      user: root
      target: toolkit 
      password: 123456
      maxIdle: 10 
      maxOpen: 5 
      showsql: True
      location: Asia/Shanghai
  mqtt:
    database:
      name: mqtt 
      type: mysql
      host: mysql.localhost
      port: 3306
      user: root
      target: toolkit 
      password: 123456
      maxIdle: 10 
      maxOpen: 5 
      showsql: True
      location: Asia/Shanghai
    params: '{"host":"mqtt-inner.roo.bo","port":1883,"qos":0,"token":"24127f62c10e84f44e5fe404552be612"}'
    lastfix: '.mqtt.robot.online'
  callback:
    database:
      name: callback 
      type: mysql
      host: mysql.localhost
      port: 3306
      user: root
      target: toolkit
      password: 123456
      maxIdle: 10 
      maxOpen: 5 
      showsql: True
      location: Asia/Shanghai
    config: '{"tongmi":[{"url":"http://tongmi.roobo.com/storybox3/notice/deviceStatus","callbackState":"custom","action":"device.info"}, {"url":"http://api.ros.ai/player/device/event","callbackState":"event","action":""}, {"url":"http://tongmi.roobo.com/storybox3/notice/deviceStatus","callbackState":"event","action":"device.info"}, {"url":"http://tongmi.roobo.com/storybox3/notice/event","callbackState":"online","action":"device.status.online"}, {"url":"http://tongmi.roobo.com/storybox3/notice/event","callbackState":"event","action":""}],"rtoy":[{"url":"http://storybox-inner.roo.bo/rtoy/mainctrls/mqttReport","callbackState":"event","action":""}, {"url":"http://storybox-inner.roo.bo/rtoy/mainctrls/mqttReport","callbackState":"custom","action":""}, {"url":"http://api.ros.ai/player/device/event","callbackState":"event","action":"sync.album.list"}]}'
  upgrade:
    database:
      name: upgrade 
      type: mysql
      host: mysql.localhost
      port: 3306
      user: root
      target: toolkit
      password: 123456
      maxIdle: 10 
      maxOpen: 5 
      showsql: True
      location: Asia/Shanghai
  album:
    database:
      name: album 
      type: mysql
      host: mysql.localhost
      port: 3306
      user: root
      target: toolkit
      password: 123456
      maxIdle: 10 
      maxOpen: 5 
      showsql: True
      location: Asia/Shanghai
  rdevice:
    database:
      name: rdevice 
      type: mysql
      host: mysql.localhost
      port: 3306
      user: root
      target: toolkit
      password: 123456
      maxIdle: 10 
      maxOpen: 5 
      showsql: True
      location: Asia/Shanghai
