app:
  mode: debug 
  BasicAuth: '{"admin":"123456"}'
storybox:
  cms:
    url: http://cms.roobo.net/api/app/copy
    supertoken: b9b065fe0714d483aa4146bb715f9895
  toolkit:
    database:
      name: toolkit 
      type: mysql
      host: mysql.localhost
      port: 3306
      user: root
      target: toolkit 
      password: 123456
      maxIdle: 10 
      maxOpen: 5 
      showsql: True
      location: Asia/Shanghai
  mqtt:
    database:
      name: mqtt 
      type: mysql
      host: mysql.localhost
      port: 3306
      user: root
      target: toolkit 
      password: 123456
      maxIdle: 10 
      maxOpen: 5 
      showsql: True
      location: Asia/Shanghai
    params: '{"host":"mqtt.roobo.net","port":1883,"qos":0,"token":"3057fcaa6a621db5640867e99907370f"}'
    lastfix: '.xxx.yyy'
  callback:
    database:
      name: callback 
      type: mysql
      host: mysql.localhost
      port: 3306
      user: root
      target: toolkit
      password: 123456
      maxIdle: 10 
      maxOpen: 5 
      showsql: True
      location: Asia/Shanghai
    config: '{"tongmi":[{"url":"xxx","callbackState":"aaa","action":"yyy"}],"rtoy":[{"url":"http://player.roobo.net/device/event","callbackState":"event","action":"sync.album.list"},{"url":"http://player.roobo.net/device/event","callbackState":"event","action":"play.control"},{"url":"http://player.roobo.net/device/event","callbackState":"event","action":"play.status.update"},{"url":"http://storybox.roobo.net/mainctrls/mqttReport","callbackState":"event","action":"device.voice.upload"},{"url":"http://storybox.roobo.net/mainctrls/mqttReport","callbackState":"event","action":""}]}'
  upgrade:
    database:
      name: upgrade 
      type: mysql
      host: mysql.localhost
      port: 3306
      user: root
      target: toolkit
      password: 123456
      maxIdle: 10 
      maxOpen: 5 
      showsql: True
      location: Asia/Shanghai
  album:
    database:
      name: album 
      type: mysql
      host: mysql.localhost
      port: 3306
      user: root
      target: toolkit
      password: 123456
      maxIdle: 10 
      maxOpen: 5 
      showsql: True
      location: Asia/Shanghai
