version: '2'
services:
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    image: mysql:5.6.38
    container_name: ${PROJECT_NAME}-${DEV_USER}-mysql
    volumes:
      - /home/${DEV_USER}/database/mysql:/var/lib/mysql
    ports:
      - "${DEV_DB_PORT}:3306"
    networks:
      - default
  backend:
    image: golang-bee:1.9
    container_name: ${PROJECT_NAME}-${DEV_USER}-golang
    volumes:
      # 挂载项目代码目录
      - ../backend:/home/roobo/go_project/src/toolkit/backend
    working_dir: /home/roobo/go_project/src/toolkit/backend
    entrypoint: 
      - bee 
      - run 
    links:
      - mysql:mysql.localhost
    ports:
      - "${DEV_PORT}:8080"
    networks:
      - default
networks:
  default:
    external:
      name: ${DEV_USER}
